### PR TITLE
bugfix: make all fields always omitempty

### PR DESCRIPTION
**Pull request by swist**
This generator has a bug/abuse of notation which
hit us pretty hard. If you have a `readOnly` and
`required` field in your OpenAPI spec then submitting
a value in the `create` payload without that field
passes validation (as you'd expect). Unfortunately
the generated serializer skips `omitempty` annotation
on required fields. As a result you when you create
a go object omitting these fields, you end up with things
like `empty string` or `0` which fail validation (even
though you're trying to submit nothing).

This looks like a confusion between a type system
(verify you construct obejcts with the correct things)
and a serializer (send the correct set of things over the
wire)

The correct behaviour seems to be to send omitemptie'd
fields always

Context and trigger for this bugfix here:
https://confluent.slack.com/archives/CULTFVBEY/p1658417580079219

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Review by codyaray — COMMENTED** [review]
I don't see the output changes anywhere. Any suggestion where to look?

**Comment by swist** [comment]
@codyaray just look at this commit: 
https://github.com/confluentinc/openapi-generator/pull/46/commits/82db00d4129a85b236a2a6293eee43ee7f131ea7
The rest is the output of 
```
./bin/generate-samples.sh
./bin/utils/export_docs_generators.sh
```

**Comment by swist** [comment]
removed the generated code from the PR

**Review by codyaray — APPROVED** [review]
fingers crossed

wdyt @linouk23 ?

**Comment by linouk23** [comment]
👏

**Comment by linouk23** [comment]
It seems like this commit caused some errors for `go vet -v` for Networking API:
```
vet: ./model_env_scoped_object_reference.go:54:12: cannot use id (variable of type string) as *string value in assignment
```
and the previous commit (`bf864e95e4`) works for Networking API.

I used `make networking/sdk/go` default command with replaced binary:
```
java -jar /Users/klinou/work/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g go \
```
and
```
mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
```
to build a jar.

**Pull request merged**
